### DISCUSSION TITLE
Vite + netlify functions

### DISCUSSION THREAD

**Discussion by nichoth** [nichoth/hermes#58] [Dev Diary]
The situation: we want to use `vite` as a dev server, and also host our netlify functions on localhost.

In `package.json`, add a script:
```js
  "scripts": {
    "start": "concurrently --kill-others \"vite\" \"npx ntl functions:serve\"",
  }
```

This will serve netlify functions on `localhost:9999`.

In the code, you need to be aware of where you are running — locally or production — and use an appropriate URL for functions depending:

```js
const { mode } = import.meta.env
const urlPrefix = (mode === 'development' ?
    (location.protocol + '//' + location.hostname + ':9999' +
        '/.netlify/functions') :
    '/api')
```

**note** this project includes a redirect
```toml
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
```
